#!/bin/sh

for d in cht disk joy kbd roms save scr set txt; do
	mkdir -p $HOME/.dingux-msx/$d
	if [ -d $HOME/emus/dingux-msx/$d ]; then
		[ `ls -A $HOME/emus/dingux-msx/$d` ] && cp -r $HOME/emus/dingux-msx/$d/* $HOME/.dingux-msx/$d/
		rm -rf $HOME/emus/dingux-msx/$d
	fi
done

[ -e $HOME/emus/dingux-msx/$d ] && mv $HOME/emus/dingux-msx/cheat.txt $HOME/.dingux-msx/

exit 0
